Test Harness Class Intialisation
Rahul-R5/KoraKaagaz pull request #14
Opened 2020-10-28 04:22 UTC by abhisheksaran

Fixes git-convict#61

2020-10-28 04:33 UTC, abhisheksaran commented
WIP...

2020-11-02 07:10 UTC, Rahul-R5 commented
@abhisheksaran Make the sync changes as requested in the #17 PR. Refer the github workflow in discord and add Manas as contributor to this branch/repo. Change destination branch to 74_test_harness. @abhisheksaran and @stalker0418, finish the test harness fast. You can't extend this till Nov 10, you need to write unit tests for each function you have written.

2020-11-02 15:17 UTC, Rahul-R5 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Test Harness function runAll](https://trello.com/c/JDv6eiah/37-test-harness-function-runall)

2020-11-02 15:19 UTC, Rahul-R5 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Test Harness functions runByName](https://trello.com/c/79Mn8dNC/36-test-harness-functions-runbyname)

2020-11-02 15:19 UTC, Rahul-R5 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Test Harness Function RunByCategory](https://trello.com/c/VdiaIF7o/31-test-harness-function-runbycategory)

2020-11-02 15:19 UTC, Rahul-R5 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Test Harness Function RunByPriority](https://trello.com/c/NY2rJZVM/30-test-harness-function-runbypriority)

2020-11-02 15:22 UTC, Rahul-R5 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Verifying Assembler Functions](https://trello.com/c/y9LhlDbd/32-verifying-assembler-functions)

2020-11-05 12:43 UTC, abhisheksaran commented
Do you want me to create another branch and delete this pull request?

2020-11-06 10:03 UTC, Rahul-R5 requested changes
Please make the required changes

2020-11-06 10:03 UTC, Rahul-R5 commented on src/infrastructure/validation/testing/TestHarness.java
> + * @author        Manas Sanjay
You can put these in the same line

2020-11-06 10:03 UTC, Rahul-R5 commented on src/infrastructure/validation/testing/TestHarness.java
> +    }
Indentation

2020-11-06 10:03 UTC, Rahul-R5 commented on src/infrastructure/validation/testing/TestHarness.java
> +	  File[] listOfTests = testFolder.listFiles();
You can reduce the code by looping through all module names. You have a lot of repeated code. This becomes unmanagable if more modules are introduced. You can read through the names of the folders in src/ and populate your module name list.

2020-11-06 10:03 UTC, Rahul-R5 commented on src/infrastructure/validation/testing/TestHarness.java
> +	  for (File file : listOfTests){
Use logger for this. Do not directly print it. Is this printing necessary?

2020-11-06 10:03 UTC, Rahul-R5 commented on src/infrastructure/validation/testing/TestHarness.java
> +  }
Test harness functions do not return anything. They only save the result.

2020-11-06 10:03 UTC, Rahul-R5 commented on src/infrastructure/validation/testing/TestHarness.java
> +    String[] arrOfStr = str.split(".", 2);
What is 'str'? If you are trying to split test name, you need to split it as [Test name] and "Test". There won't be any punctuations. We have removed the underscore naming too.

2020-11-07 05:52 UTC, Rahul-R5 commented on src/infrastructure/validation/testing/TestHarness.java
> +  }
This result will be needed. Ignore the previous comment

2020-11-10 05:28 UTC, abhisheksaran commented
RunAll() and runByName() are done.

2020-11-26 05:58 UTC, Rahul-R5 commented
Outdated

2020-11-26 05:58 UTC, closed without merging